services:
  backend:
    build: .
    container_name: autosnab_backend_mvp4
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # В контейнере путь к JSON отличается от локального запуска.
      GOOGLE_SERVICE_ACCOUNT_FILE: /app/secrets/service-account.json
      UPLOADED_INVOICES_DIR: /app/uploads/invoices
    volumes:
      - ./backend/secrets:/app/secrets:ro
      - ./backend/uploads:/app/uploads
